twig:
    form_themes: ['bootstrap_4_layout.html.twig', '_form_layout.html.twig']
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        app_name: '%env(APP_NAME)%'
        app_goal: '%env(APP_GOAL)%'
        app_extra_text: '%env(APP_EXTRA_TEXT)%'
