build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}"
      --destination "${CI_REGISTRY_IMAGE}:latest"

promote:
  stage: deploy
  image:
    name: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -qq update && apt-get -qq -y --no-install-recommends install openssh-client rsync
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - ls -l $SSH_PRIVATE_KEY $SSH_KNOWN_HOSTS
    - mv $SSH_PRIVATE_KEY ~/.ssh/id_rsa
    - mv $SSH_KNOWN_HOSTS ~/.ssh/known_hosts
    - chmod go-rwx -R ~/.ssh
  script:
    - cd /app
    - rsync -rtl COPYING README.md assets bin composer.json composer.lock config migrations public src templates vendor m3621@web15.biohost.net:/home/m3621/Sites/backend.timetable.wueww.de/
    - ssh m3621@web15.biohost.net "cd Sites/backend.timetable.wueww.de && php7.4 bin/console cache:clear && php7.4 bin/console cache:warmup && php7.4 bin/console doc:mig:mig -vv --no-interaction"
